apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: ns-dev
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "100m"
      memory: "10Mi"
    default:
      cpu: "200m"
      memory: "20Mi"
    max:
      cpu: "200m"
      memory: "256Mi"

